spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

