spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
    publisher-confirms: true


mybatis:
  mapperLocations: classpath:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

redis:
  host: localhost
  port: 6379
  timeout: 100
  password: 123456
  poolMaxTotal: 1000
  pollMaxIdle: 500
  pollMaxWait: 500

